[package]
name = "semtag"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = "symbols"
panic = "abort"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
git2 = "0.20.0"
semver = "1.0.24"
